import {
  AssessmentDimension,
  CareerDifficulty,
  DemandLevel,
  PrismaClient,
  RoadmapItemType,
} from "@prisma/client";

const prisma = new PrismaClient();

const DEMO_SALARY_DISCLAIMER =
  "Illustrative sample/demo figures only; actual compensation varies by role, employer, location, and experience.";
const DEMO_DEMAND_DISCLAIMER =
  "Illustrative demo indicator only; demand can change by location, employer, and time.";

type SkillSeed = {
  slug: string;
  name: string;
  targetLevel: number;
  importance: number;
  isTechnical?: boolean;
};

type CareerSeed = {
  slug: string;
  name: string;
  category: string;
  overview: string;
  whatProfessionalsDo: string;
  whyChoose: string;
  educationSummary: string;
  salary: [number, number];
  demandLevel: DemandLevel;
  difficulty: CareerDifficulty;
  workLifeBalance: number;
  growthPotential: number;
  governmentOpportunity: number;
  remoteWorkPotential: number;
  entranceExams: string[];
  certifications: string[];
  recommendedCourses: string[];
  progression: string[];
  relatedCareers: string[];
  skills: SkillSeed[];
  fit: {
    interestTargets: Record<string, number>;
    personalityTargets: Record<string, number>;
    valueTargets: Record<string, number>;
    workPreferenceTargets: Record<string, number>;
    academicProfile: {
      minimumEducationLevel?: string;
      preferredStreams?: string[];
      minimumAcademicScore?: number;
    };
  };
};

const CATEGORIES = [
  ["technology", "Technology", "Build and operate digital products and platforms."],
  ["data-ai", "Data & AI", "Turn data into useful evidence, models, and decisions."],
  ["engineering", "Engineering", "Design, build, and improve physical and technical systems."],
  ["healthcare", "Healthcare", "Support health, wellbeing, and clinical care."],
  ["finance", "Finance & Accounting", "Analyse, manage, and advise on financial matters."],
  ["management", "Management & Business", "Plan products, teams, operations, and strategy."],
  ["government", "Government & Public Administration", "Serve public institutions and communities."],
  ["law", "Law", "Interpret law, resolve disputes, and advise people or organisations."],
  ["design", "Design & Built Environment", "Shape usable experiences, spaces, and visual systems."],
  ["media", "Media & Communication", "Create, distribute, and measure meaningful communication."],
  ["education", "Education", "Help people learn and develop."],
  ["research", "Research", "Investigate questions and create reliable knowledge."],
  ["entrepreneurship", "Entrepreneurship", "Create and grow ventures that solve real problems."],
] as const;

const CAREERS: CareerSeed[] = [
  {
    slug: "software-engineer",
    name: "Software Engineer",
    category: "technology",
    overview: "Software engineers design, build, test, and maintain applications and digital systems.",
    whatProfessionalsDo: "They translate requirements into reliable code, collaborate with product and design teams, review changes, and improve system quality.",
    whyChoose: "A potentially suitable path for people who enjoy structured problem-solving, creating useful tools, and continuous learning.",
    educationSummary: "Common routes include a computing or engineering degree, diploma, self-directed learning, and demonstrable project experience.",
    salary: [450000, 1200000],
    demandLevel: DemandLevel.HIGH,
    difficulty: CareerDifficulty.MODERATE,
    workLifeBalance: 3,
    growthPotential: 5,
    governmentOpportunity: 2,
    remoteWorkPotential: 5,
    entranceExams: ["Institution-specific engineering or computing admissions"],
    certifications: ["Cloud fundamentals", "Secure coding foundations"],
    recommendedCourses: ["Programming fundamentals", "Data structures", "Web or application development"],
    progression: ["Junior Engineer", "Software Engineer", "Senior Engineer", "Technical Lead or Architect"],
    relatedCareers: ["cloud-engineer", "cybersecurity-analyst", "product-manager"],
    skills: [
      { slug: "programming", name: "Programming", targetLevel: 80, importance: 95, isTechnical: true },
      { slug: "data-structures", name: "Data Structures", targetLevel: 70, importance: 80, isTechnical: true },
      { slug: "problem-solving", name: "Problem Solving", targetLevel: 80, importance: 90 },
      { slug: "collaboration", name: "Collaboration", targetLevel: 65, importance: 60 },
    ],
    fit: {
      interestTargets: { technology: 90, mathematics: 70, problemSolving: 90 },
      personalityTargets: { analyticalThinking: 85, structurePreference: 65, independence: 70 },
      valueTargets: { growth: 85, intellectualChallenge: 85, salary: 65 },
      workPreferenceTargets: { peopleVsSystems: 30, analyticalVsCreative: 30, remoteHybridPreference: 75 },
      academicProfile: { minimumEducationLevel: "UNDERGRADUATE", preferredStreams: ["science", "computer science", "engineering"] },
    },
  },
  {
    slug: "data-analyst",
    name: "Data Analyst",
    category: "data-ai",
    overview: "Data analysts organise, explore, and communicate data to support better decisions.",
    whatProfessionalsDo: "They clean data, write queries, build reports, explain patterns, and partner with teams to answer practical questions.",
    whyChoose: "Worth exploring for people who enjoy evidence, business context, and making complex information easier to understand.",
    educationSummary: "Routes may include analytics, economics, commerce, mathematics, engineering, or portfolio-based upskilling.",
    salary: [400000, 1000000],
    demandLevel: DemandLevel.HIGH,
    difficulty: CareerDifficulty.MODERATE,
    workLifeBalance: 4,
    growthPotential: 4,
    governmentOpportunity: 2,
    remoteWorkPotential: 4,
    entranceExams: ["Institution-specific analytics admissions"],
    certifications: ["Data analytics fundamentals", "Business intelligence foundations"],
    recommendedCourses: ["Spreadsheet analysis", "SQL", "Statistics", "Data visualisation"],
    progression: ["Junior Analyst", "Data Analyst", "Senior Analyst", "Analytics Lead"],
    relatedCareers: ["data-scientist", "business-analyst", "financial-analyst"],
    skills: [
      { slug: "sql", name: "SQL", targetLevel: 80, importance: 95, isTechnical: true },
      { slug: "statistics", name: "Statistics", targetLevel: 70, importance: 85, isTechnical: true },
      { slug: "data-visualisation", name: "Data Visualisation", targetLevel: 75, importance: 80, isTechnical: true },
      { slug: "communication", name: "Communication", targetLevel: 70, importance: 70 },
    ],
    fit: {
      interestTargets: { data: 95, mathematics: 80, business: 65, research: 70 },
      personalityTargets: { analyticalThinking: 90, structurePreference: 75, collaboration: 65 },
      valueTargets: { intellectualChallenge: 75, growth: 75, workLifeBalance: 65 },
      workPreferenceTargets: { peopleVsSystems: 45, analyticalVsCreative: 25, remoteHybridPreference: 70 },
      academicProfile: { minimumEducationLevel: "UNDERGRADUATE", preferredStreams: ["science", "commerce", "economics", "mathematics", "engineering"] },
    },
  },
  {
    slug: "data-scientist",
    name: "Data Scientist",
    category: "data-ai",
    overview: "Data scientists use statistics, programming, and domain context to investigate data and build predictive or decision-support models.",
    whatProfessionalsDo: "They frame questions, prepare datasets, experiment with models, validate results, and communicate limits and findings.",
    whyChoose: "Potentially suitable for people who enjoy rigorous analysis, research, and using data to solve uncertain problems.",
    educationSummary: "Common backgrounds include statistics, mathematics, computer science, engineering, economics, or a related postgraduate route.",
    salary: [600000, 1500000],
    demandLevel: DemandLevel.HIGH,
    difficulty: CareerDifficulty.ADVANCED,
    workLifeBalance: 3,
    growthPotential: 5,
    governmentOpportunity: 2,
    remoteWorkPotential: 4,
    entranceExams: ["Institution-specific postgraduate admissions"],
    certifications: ["Machine learning foundations", "Cloud data foundations"],
    recommendedCourses: ["Probability", "Python", "Machine learning", "Experiment design"],
    progression: ["Data Analyst", "Data Scientist", "Senior Data Scientist", "Principal or Analytics Lead"],
    relatedCareers: ["machine-learning-engineer", "data-analyst", "research-scientist"],
    skills: [
      { slug: "python", name: "Python", targetLevel: 80, importance: 85, isTechnical: true },
      { slug: "statistics", name: "Statistics", targetLevel: 85, importance: 95, isTechnical: true },
      { slug: "machine-learning", name: "Machine Learning", targetLevel: 75, importance: 85, isTechnical: true },
      { slug: "research-methods", name: "Research Methods", targetLevel: 70, importance: 70 },
    ],
    fit: {
      interestTargets: { data: 95, mathematics: 90, science: 75, research: 90 },
      personalityTargets: { analyticalThinking: 95, independence: 75, creativity: 60 },
      valueTargets: { intellectualChallenge: 90, growth: 85, independence: 65 },
      workPreferenceTargets: { peopleVsSystems: 25, analyticalVsCreative: 20, remoteHybridPreference: 65 },
      academicProfile: { minimumEducationLevel: "UNDERGRADUATE", preferredStreams: ["science", "mathematics", "statistics", "computer science", "engineering"] },
    },
  },
  {
    slug: "machine-learning-engineer",
    name: "Machine Learning Engineer",
    category: "data-ai",
    overview: "Machine learning engineers turn data models into dependable systems that can be evaluated, deployed, and monitored.",
    whatProfessionalsDo: "They build training pipelines, integrate models into software, monitor quality, and collaborate with data and engineering teams.",
    whyChoose: "A demanding but potentially fitting path for people drawn to coding, maths, experimentation, and production systems.",
    educationSummary: "Often entered through computer science, engineering, data science, or focused postgraduate and project-based preparation.",
    salary: [700000, 1800000],
    demandLevel: DemandLevel.HIGH,
    difficulty: CareerDifficulty.ADVANCED,
    workLifeBalance: 3,
    growthPotential: 5,
    governmentOpportunity: 1,
    remoteWorkPotential: 4,
    entranceExams: ["Institution-specific technical admissions"],
    certifications: ["Cloud machine learning foundations", "MLOps foundations"],
    recommendedCourses: ["Algorithms", "Python", "Machine learning", "MLOps"],
    progression: ["Software or Data Engineer", "ML Engineer", "Senior ML Engineer", "ML Platform Lead"],
    relatedCareers: ["data-scientist", "software-engineer", "cloud-engineer"],
    skills: [
      { slug: "python", name: "Python", targetLevel: 85, importance: 85, isTechnical: true },
      { slug: "machine-learning", name: "Machine Learning", targetLevel: 85, importance: 95, isTechnical: true },
      { slug: "software-engineering", name: "Software Engineering", targetLevel: 75, importance: 85, isTechnical: true },
      { slug: "data-engineering", name: "Data Engineering", targetLevel: 70, importance: 75, isTechnical: true },
    ],
    fit: {
      interestTargets: { technology: 95, data: 95, mathematics: 85, research: 75 },
      personalityTargets: { analyticalThinking: 95, structurePreference: 70, independence: 70 },
      valueTargets: { intellectualChallenge: 95, growth: 90, salary: 70 },
      workPreferenceTargets: { peopleVsSystems: 20, analyticalVsCreative: 20, remoteHybridPreference: 70 },
      academicProfile: { minimumEducationLevel: "UNDERGRADUATE", preferredStreams: ["computer science", "engineering", "mathematics", "data science"] },
    },
  },
  {
    slug: "cybersecurity-analyst",
    name: "Cybersecurity Analyst",
    category: "technology",
    overview: "Cybersecurity analysts help organisations identify, reduce, and respond to digital security risks.",
    whatProfessionalsDo: "They monitor alerts, investigate incidents, strengthen controls, document findings, and promote secure practices.",
    whyChoose: "Potentially suitable for people who enjoy systems thinking, investigation, ethical responsibility, and careful problem-solving.",
    educationSummary: "Entry routes include computing, engineering, IT diplomas, labs, certifications, and practical security projects.",
    salary: [500000, 1300000],
    demandLevel: DemandLevel.HIGH,
    difficulty: CareerDifficulty.ADVANCED,
    workLifeBalance: 3,
    growthPotential: 5,
    governmentOpportunity: 3,
    remoteWorkPotential: 3,
    entranceExams: ["Institution-specific IT or engineering admissions"],
    certifications: ["Security fundamentals", "Network security foundations"],
    recommendedCourses: ["Networking", "Operating systems", "Secure coding", "Incident response"],
    progression: ["Security Associate", "Security Analyst", "Security Engineer", "Security Lead"],
    relatedCareers: ["software-engineer", "cloud-engineer", "government-officer"],
    skills: [
      { slug: "networking", name: "Networking", targetLevel: 75, importance: 85, isTechnical: true },
      { slug: "security-analysis", name: "Security Analysis", targetLevel: 80, importance: 95, isTechnical: true },
      { slug: "risk-assessment", name: "Risk Assessment", targetLevel: 70, importance: 75 },
      { slug: "attention-to-detail", name: "Attention to Detail", targetLevel: 80, importance: 80 },
    ],
    fit: {
      interestTargets: { technology: 90, research: 65, problemSolving: 85 },
      personalityTargets: { analyticalThinking: 85, structurePreference: 80, stabilityPreference: 65 },
      valueTargets: { jobSecurity: 75, intellectualChallenge: 80, socialImpact: 60 },
      workPreferenceTargets: { peopleVsSystems: 30, analyticalVsCreative: 20, remoteHybridPreference: 55 },
      academicProfile: { minimumEducationLevel: "UNDERGRADUATE", preferredStreams: ["computer science", "information technology", "engineering"] },
    },
  },
  {
    slug: "cloud-engineer",
    name: "Cloud Engineer",
    category: "technology",
    overview: "Cloud engineers design and operate scalable computing infrastructure and developer platforms.",
    whatProfessionalsDo: "They automate deployments, configure cloud services, improve reliability, and collaborate on secure operations.",
    whyChoose: "Worth exploring for technically curious people who like systems, automation, and making teams more effective.",
    educationSummary: "Common pathways combine an IT or engineering background, Linux and networking knowledge, cloud labs, and projects.",
    salary: [550000, 1400000],
    demandLevel: DemandLevel.HIGH,
    difficulty: CareerDifficulty.ADVANCED,
    workLifeBalance: 3,
    growthPotential: 5,
    governmentOpportunity: 2,
    remoteWorkPotential: 4,
    entranceExams: ["Institution-specific IT or engineering admissions"],
    certifications: ["Cloud practitioner or associate credentials", "Linux foundations"],
    recommendedCourses: ["Linux", "Networking", "Cloud fundamentals", "Infrastructure automation"],
    progression: ["Systems Associate", "Cloud Engineer", "Senior Cloud Engineer", "Platform Architect"],
    relatedCareers: ["software-engineer", "cybersecurity-analyst", "machine-learning-engineer"],
    skills: [
      { slug: "cloud-platforms", name: "Cloud Platforms", targetLevel: 80, importance: 95, isTechnical: true },
      { slug: "linux", name: "Linux", targetLevel: 70, importance: 75, isTechnical: true },
      { slug: "networking", name: "Networking", targetLevel: 70, importance: 70, isTechnical: true },
      { slug: "automation", name: "Automation", targetLevel: 75, importance: 85, isTechnical: true },
    ],
    fit: {
      interestTargets: { technology: 95, engineering: 75, problemSolving: 85 },
      personalityTargets: { analyticalThinking: 85, structurePreference: 75, independence: 70 },
      valueTargets: { growth: 85, intellectualChallenge: 80, jobSecurity: 65 },
      workPreferenceTargets: { peopleVsSystems: 25, analyticalVsCreative: 25, remoteHybridPreference: 70 },
      academicProfile: { minimumEducationLevel: "UNDERGRADUATE", preferredStreams: ["computer science", "information technology", "engineering"] },
    },
  },
  {
    slug: "business-analyst",
    name: "Business Analyst",
    category: "management",
    overview: "Business analysts clarify business needs and help teams use information and processes to improve outcomes.",
    whatProfessionalsDo: "They interview stakeholders, map processes, analyse data, document requirements, and support practical change.",
    whyChoose: "Potentially suitable for people who like both analytical work and conversations with different teams.",
    educationSummary: "Routes include business, economics, commerce, engineering, information systems, or relevant experience and a portfolio.",
    salary: [450000, 1100000],
    demandLevel: DemandLevel.HIGH,
    difficulty: CareerDifficulty.MODERATE,
    workLifeBalance: 4,
    growthPotential: 4,
    governmentOpportunity: 2,
    remoteWorkPotential: 4,
    entranceExams: ["Institution-specific business or analytics admissions"],
    certifications: ["Business analysis foundations", "Agile foundations"],
    recommendedCourses: ["Business process analysis", "Spreadsheets", "SQL", "Stakeholder communication"],
    progression: ["Analyst", "Business Analyst", "Senior Business Analyst", "Product or Strategy Lead"],
    relatedCareers: ["data-analyst", "product-manager", "financial-analyst"],
    skills: [
      { slug: "requirements-analysis", name: "Requirements Analysis", targetLevel: 80, importance: 90 },
      { slug: "communication", name: "Communication", targetLevel: 80, importance: 90 },
      { slug: "sql", name: "SQL", targetLevel: 60, importance: 60, isTechnical: true },
      { slug: "problem-solving", name: "Problem Solving", targetLevel: 75, importance: 80 },
    ],
    fit: {
      interestTargets: { business: 85, data: 65, communication: 85, leadership: 60 },
      personalityTargets: { analyticalThinking: 80, collaboration: 85, structurePreference: 70 },
      valueTargets: { growth: 75, workLifeBalance: 65, intellectualChallenge: 70 },
      workPreferenceTargets: { peopleVsSystems: 65, analyticalVsCreative: 45, remoteHybridPreference: 65 },
      academicProfile: { minimumEducationLevel: "UNDERGRADUATE", preferredStreams: ["commerce", "business", "economics", "engineering", "science"] },
    },
  },
  {
    slug: "product-manager",
    name: "Product Manager",
    category: "management",
    overview: "Product managers guide a product's direction by balancing user needs, business goals, and delivery realities.",
    whatProfessionalsDo: "They prioritise problems, align stakeholders, define outcomes, learn from users, and work closely with design and engineering.",
    whyChoose: "Worth exploring for people who enjoy ownership, ambiguity, communication, and bringing diverse work together.",
    educationSummary: "People enter from engineering, design, business, analytics, operations, or domain experience; evidence of product thinking is valuable.",
    salary: [650000, 1600000],
    demandLevel: DemandLevel.HIGH,
    difficulty: CareerDifficulty.ADVANCED,
    workLifeBalance: 3,
    growthPotential: 5,
    governmentOpportunity: 1,
    remoteWorkPotential: 4,
    entranceExams: ["Institution-specific management admissions"],
    certifications: ["Product management foundations", "Agile foundations"],
    recommendedCourses: ["Product discovery", "User research", "Analytics", "Communication"],
    progression: ["Associate Product Manager", "Product Manager", "Senior Product Manager", "Product Lead"],
    relatedCareers: ["business-analyst", "ui-ux-designer", "entrepreneur"],
    skills: [
      { slug: "product-thinking", name: "Product Thinking", targetLevel: 80, importance: 95 },
      { slug: "stakeholder-management", name: "Stakeholder Management", targetLevel: 80, importance: 90 },
      { slug: "user-research", name: "User Research", targetLevel: 70, importance: 75 },
      { slug: "data-literacy", name: "Data Literacy", targetLevel: 65, importance: 65 },
    ],
    fit: {
      interestTargets: { business: 85, technology: 65, leadership: 90, communication: 90 },
      personalityTargets: { leadership: 90, collaboration: 95, riskTolerance: 65, creativity: 65 },
      valueTargets: { growth: 90, intellectualChallenge: 75, independence: 65 },
      workPreferenceTargets: { peopleVsSystems: 75, analyticalVsCreative: 55, remoteHybridPreference: 65 },
      academicProfile: { minimumEducationLevel: "UNDERGRADUATE", preferredStreams: ["business", "engineering", "design", "science", "commerce"] },
    },
  },
  {
    slug: "ui-ux-designer",
    name: "UI/UX Designer",
    category: "design",
    overview: "UI/UX designers research users and create clear, accessible digital experiences.",
    whatProfessionalsDo: "They conduct research, map flows, prototype interfaces, test ideas, and collaborate with product and engineering teams.",
    whyChoose: "Potentially suitable for people who combine curiosity about people with visual communication and structured creativity.",
    educationSummary: "Routes include design degrees, bootcamps, self-directed study, and a portfolio that shows research and problem-solving.",
    salary: [400000, 1000000],
    demandLevel: DemandLevel.HIGH,
    difficulty: CareerDifficulty.MODERATE,
    workLifeBalance: 4,
    growthPotential: 4,
    governmentOpportunity: 1,
    remoteWorkPotential: 4,
    entranceExams: ["Institution-specific design admissions"],
    certifications: ["Accessibility foundations", "Interaction design foundations"],
    recommendedCourses: ["Design fundamentals", "User research", "Prototyping", "Accessibility"],
    progression: ["Junior Designer", "UI/UX Designer", "Senior Designer", "Design Lead"],
    relatedCareers: ["product-manager", "architect", "digital-marketer"],
    skills: [
      { slug: "user-research", name: "User Research", targetLevel: 75, importance: 80 },
      { slug: "interaction-design", name: "Interaction Design", targetLevel: 80, importance: 90, isTechnical: true },
      { slug: "visual-design", name: "Visual Design", targetLevel: 75, importance: 80 },
      { slug: "prototyping", name: "Prototyping", targetLevel: 70, importance: 70, isTechnical: true },
    ],
    fit: {
      interestTargets: { creativity: 95, design: 95, communication: 70, technology: 60 },
      personalityTargets: { creativity: 95, collaboration: 75, empathy: 85, structurePreference: 55 },
      valueTargets: { intellectualChallenge: 70, workLifeBalance: 65, growth: 75 },
      workPreferenceTargets: { peopleVsSystems: 65, analyticalVsCreative: 80, remoteHybridPreference: 70 },
      academicProfile: { minimumEducationLevel: "UNDERGRADUATE", preferredStreams: ["design", "arts", "engineering", "computer science"] },
    },
  },
  {
    slug: "chartered-accountant",
    name: "Chartered Accountant",
    category: "finance",
    overview: "Chartered accountants support financial reporting, audit, tax, compliance, and business decision-making.",
    whatProfessionalsDo: "They analyse financial records, apply standards, advise clients or teams, and ensure reliable reporting and controls.",
    whyChoose: "A structured pathway for people who enjoy finance, detail, accountability, and long-term professional development.",
    educationSummary: "This pathway is governed by professional bodies and evolving official requirements; verify the current route directly with the relevant authority.",
    salary: [500000, 1400000],
    demandLevel: DemandLevel.HIGH,
    difficulty: CareerDifficulty.ADVANCED,
    workLifeBalance: 3,
    growthPotential: 5,
    governmentOpportunity: 3,
    remoteWorkPotential: 2,
    entranceExams: ["Professional body examinations; verify current official requirements"],
    certifications: ["Professional accounting qualifications; verify current official requirements"],
    recommendedCourses: ["Financial accounting", "Taxation", "Audit", "Business law"],
    progression: ["Article or Trainee", "Qualified Accountant", "Manager", "Partner or Finance Leader"],
    relatedCareers: ["financial-analyst", "investment-banker", "government-officer"],
    skills: [
      { slug: "accounting", name: "Accounting", targetLevel: 90, importance: 95, isTechnical: true },
      { slug: "financial-reporting", name: "Financial Reporting", targetLevel: 80, importance: 90, isTechnical: true },
      { slug: "attention-to-detail", name: "Attention to Detail", targetLevel: 85, importance: 85 },
      { slug: "ethics", name: "Professional Ethics", targetLevel: 80, importance: 85 },
    ],
    fit: {
      interestTargets: { finance: 95, mathematics: 70, business: 75, law: 55 },
      personalityTargets: { structurePreference: 90, analyticalThinking: 85, stabilityPreference: 70 },
      valueTargets: { jobSecurity: 80, prestige: 70, salary: 70 },
      workPreferenceTargets: { peopleVsSystems: 45, analyticalVsCreative: 25, remoteHybridPreference: 35 },
      academicProfile: { minimumEducationLevel: "CLASS_12", preferredStreams: ["commerce", "business", "mathematics"] },
    },
  },
  {
    slug: "financial-analyst",
    name: "Financial Analyst",
    category: "finance",
    overview: "Financial analysts examine financial information to help organisations plan, evaluate options, and manage performance.",
    whatProfessionalsDo: "They build models, interpret statements, prepare reports, track performance, and communicate financial insights.",
    whyChoose: "Worth exploring for people who enjoy numerical reasoning, business questions, and clear evidence-based communication.",
    educationSummary: "Common routes include finance, commerce, economics, mathematics, accounting, business, or analytical experience.",
    salary: [450000, 1150000],
    demandLevel: DemandLevel.HIGH,
    difficulty: CareerDifficulty.MODERATE,
    workLifeBalance: 3,
    growthPotential: 4,
    governmentOpportunity: 2,
    remoteWorkPotential: 3,
    entranceExams: ["Institution-specific commerce, economics, or finance admissions"],
    certifications: ["Financial modelling foundations", "Investment analysis foundations"],
    recommendedCourses: ["Corporate finance", "Financial modelling", "Spreadsheets", "Accounting"],
    progression: ["Analyst", "Senior Analyst", "Finance Manager", "Finance Lead"],
    relatedCareers: ["chartered-accountant", "investment-banker", "data-analyst"],
    skills: [
      { slug: "financial-modelling", name: "Financial Modelling", targetLevel: 80, importance: 90, isTechnical: true },
      { slug: "accounting", name: "Accounting", targetLevel: 70, importance: 75, isTechnical: true },
      { slug: "spreadsheets", name: "Spreadsheets", targetLevel: 80, importance: 80, isTechnical: true },
      { slug: "communication", name: "Communication", targetLevel: 65, importance: 60 },
    ],
    fit: {
      interestTargets: { finance: 95, mathematics: 75, business: 80, data: 65 },
      personalityTargets: { analyticalThinking: 90, structurePreference: 80, collaboration: 60 },
      valueTargets: { salary: 70, growth: 75, intellectualChallenge: 75 },
      workPreferenceTargets: { peopleVsSystems: 40, analyticalVsCreative: 25, remoteHybridPreference: 45 },
      academicProfile: { minimumEducationLevel: "UNDERGRADUATE", preferredStreams: ["commerce", "finance", "economics", "business", "mathematics"] },
    },
  },
  {
    slug: "investment-banker",
    name: "Investment Banker",
    category: "finance",
    overview: "Investment bankers advise organisations on capital raising, transactions, and complex financial decisions.",
    whatProfessionalsDo: "They analyse businesses, prepare financial materials, support transactions, and work closely with clients and specialists.",
    whyChoose: "A high-intensity path to explore if you value finance, commercial problem-solving, demanding teamwork, and fast learning.",
    educationSummary: "Routes commonly include finance, economics, commerce, business, engineering, and relevant internships; hiring criteria vary by employer.",
    salary: [700000, 2000000],
    demandLevel: DemandLevel.MODERATE,
    difficulty: CareerDifficulty.ADVANCED,
    workLifeBalance: 1,
    growthPotential: 5,
    governmentOpportunity: 1,
    remoteWorkPotential: 1,
    entranceExams: ["Institution-specific business or finance admissions"],
    certifications: ["Financial modelling foundations", "Investment analysis foundations"],
    recommendedCourses: ["Corporate finance", "Valuation", "Accounting", "Presentation skills"],
    progression: ["Analyst", "Associate", "Vice President", "Director or Managing Director"],
    relatedCareers: ["financial-analyst", "chartered-accountant", "entrepreneur"],
    skills: [
      { slug: "financial-modelling", name: "Financial Modelling", targetLevel: 85, importance: 95, isTechnical: true },
      { slug: "valuation", name: "Valuation", targetLevel: 80, importance: 85, isTechnical: true },
      { slug: "presentation", name: "Presentation", targetLevel: 80, importance: 75 },
      { slug: "resilience", name: "Resilience", targetLevel: 80, importance: 75 },
    ],
    fit: {
      interestTargets: { finance: 95, business: 90, mathematics: 75, leadership: 65 },
      personalityTargets: { analyticalThinking: 90, riskTolerance: 75, collaboration: 85, resilience: 85 },
      valueTargets: { salary: 90, prestige: 80, growth: 90 },
      workPreferenceTargets: { peopleVsSystems: 65, analyticalVsCreative: 35, remoteHybridPreference: 15 },
      academicProfile: { minimumEducationLevel: "UNDERGRADUATE", preferredStreams: ["finance", "economics", "commerce", "business", "engineering"] },
    },
  },
  {
    slug: "civil-services-officer",
    name: "Civil Services Officer",
    category: "government",
    overview: "Civil services officers support public administration, policy implementation, and service delivery across government roles.",
    whatProfessionalsDo: "Work can include administration, programme delivery, coordination, public engagement, crisis response, and policy support.",
    whyChoose: "Potentially suitable for people motivated by public service, broad learning, leadership, and long-term community impact.",
    educationSummary: "Selection routes and eligibility rules change; consult current official notices before planning a preparation pathway.",
    salary: [600000, 1300000],
    demandLevel: DemandLevel.MODERATE,
    difficulty: CareerDifficulty.ADVANCED,
    workLifeBalance: 3,
    growthPotential: 4,
    governmentOpportunity: 5,
    remoteWorkPotential: 1,
    entranceExams: ["UPSC Civil Services Examination; verify current official eligibility and syllabus"],
    certifications: ["Public policy or governance courses"],
    recommendedCourses: ["Indian polity", "Economics", "Public administration", "Writing and ethics"],
    progression: ["Training", "Field or Secretariat Roles", "Senior Administration", "Policy Leadership"],
    relatedCareers: ["indian-police-service-officer", "government-officer", "lawyer"],
    skills: [
      { slug: "public-administration", name: "Public Administration", targetLevel: 80, importance: 90 },
      { slug: "writing", name: "Writing", targetLevel: 80, importance: 80 },
      { slug: "leadership", name: "Leadership", targetLevel: 75, importance: 80 },
      { slug: "policy-analysis", name: "Policy Analysis", targetLevel: 70, importance: 75 },
    ],
    fit: {
      interestTargets: { publicAdministration: 95, socialService: 90, leadership: 80, research: 65 },
      personalityTargets: { leadership: 85, resilience: 80, collaboration: 80, stabilityPreference: 65 },
      valueTargets: { socialImpact: 95, prestige: 70, jobSecurity: 75 },
      workPreferenceTargets: { peopleVsSystems: 85, analyticalVsCreative: 45, governmentVsPrivate: 95, remoteHybridPreference: 10 },
      academicProfile: { minimumEducationLevel: "GRADUATE" },
    },
  },
  {
    slug: "indian-police-service-officer",
    name: "Indian Police Service Officer",
    category: "government",
    overview: "Police service officers lead public-safety, investigation, and administrative responsibilities within legal and institutional frameworks.",
    whatProfessionalsDo: "Responsibilities may involve leadership, coordination, field operations, community engagement, and emergency response.",
    whyChoose: "A demanding public-service path for people with resilience, leadership potential, and a strong sense of responsibility.",
    educationSummary: "Selection and eligibility are governed by official processes that can change; verify current information with the relevant authority.",
    salary: [600000, 1300000],
    demandLevel: DemandLevel.MODERATE,
    difficulty: CareerDifficulty.ADVANCED,
    workLifeBalance: 2,
    growthPotential: 4,
    governmentOpportunity: 5,
    remoteWorkPotential: 1,
    entranceExams: ["UPSC Civil Services Examination; verify current official eligibility and syllabus"],
    certifications: ["Public safety and leadership learning"],
    recommendedCourses: ["Public administration", "Law and ethics", "Physical fitness", "Current affairs"],
    progression: ["Training", "Field Leadership", "Senior Command", "Policy or Administration Leadership"],
    relatedCareers: ["civil-services-officer", "government-officer", "lawyer"],
    skills: [
      { slug: "leadership", name: "Leadership", targetLevel: 85, importance: 90 },
      { slug: "decision-making", name: "Decision Making", targetLevel: 80, importance: 85 },
      { slug: "communication", name: "Communication", targetLevel: 75, importance: 75 },
      { slug: "resilience", name: "Resilience", targetLevel: 90, importance: 90 },
    ],
    fit: {
      interestTargets: { publicAdministration: 85, socialService: 90, leadership: 90 },
      personalityTargets: { leadership: 95, resilience: 95, riskTolerance: 75, collaboration: 75 },
      valueTargets: { socialImpact: 95, jobSecurity: 75, prestige: 75 },
      workPreferenceTargets: { peopleVsSystems: 90, analyticalVsCreative: 40, governmentVsPrivate: 95, remoteHybridPreference: 5 },
      academicProfile: { minimumEducationLevel: "GRADUATE" },
    },
  },
  {
    slug: "lawyer",
    name: "Lawyer",
    category: "law",
    overview: "Lawyers interpret law, advise clients, research issues, draft documents, and represent interests in legal processes.",
    whatProfessionalsDo: "Their work may involve client interviews, legal research, drafting, negotiation, compliance, or advocacy depending on the practice area.",
    whyChoose: "Worth exploring for people who enjoy careful reasoning, language, public issues, and structured argument.",
    educationSummary: "Legal education and licensing requirements vary by institution and jurisdiction; check current rules with official bodies.",
    salary: [400000, 1200000],
    demandLevel: DemandLevel.MODERATE,
    difficulty: CareerDifficulty.ADVANCED,
    workLifeBalance: 3,
    growthPotential: 4,
    governmentOpportunity: 4,
    remoteWorkPotential: 2,
    entranceExams: ["Law entrance examinations or institution-specific admissions; verify current official details"],
    certifications: ["Mediation or compliance foundations"],
    recommendedCourses: ["Legal research", "Writing", "Constitutional law", "Negotiation"],
    progression: ["Law Student or Intern", "Associate", "Senior Associate", "Counsel or Partner"],
    relatedCareers: ["civil-services-officer", "government-officer", "psychologist"],
    skills: [
      { slug: "legal-research", name: "Legal Research", targetLevel: 85, importance: 90 },
      { slug: "writing", name: "Writing", targetLevel: 85, importance: 85 },
      { slug: "argumentation", name: "Argumentation", targetLevel: 80, importance: 85 },
      { slug: "negotiation", name: "Negotiation", targetLevel: 70, importance: 70 },
    ],
    fit: {
      interestTargets: { law: 95, writing: 90, publicAdministration: 65, communication: 85 },
      personalityTargets: { analyticalThinking: 90, independence: 75, resilience: 70 },
      valueTargets: { intellectualChallenge: 85, socialImpact: 70, prestige: 65 },
      workPreferenceTargets: { peopleVsSystems: 75, analyticalVsCreative: 45, governmentVsPrivate: 55, remoteHybridPreference: 25 },
      academicProfile: { minimumEducationLevel: "CLASS_12", preferredStreams: ["arts", "humanities", "commerce", "science"] },
    },
  },
  {
    slug: "doctor",
    name: "Doctor",
    category: "healthcare",
    overview: "Doctors assess health concerns, make clinical decisions, communicate with patients, and work within multidisciplinary care teams.",
    whatProfessionalsDo: "Their work includes clinical assessment, treatment planning, patient education, documentation, and ongoing professional learning.",
    whyChoose: "A long, rigorous path for people drawn to science, service, responsibility, and sustained work with people.",
    educationSummary: "Medical education, licensing, entrance examinations, and specialisation routes are regulated and must be verified through current official sources.",
    salary: [600000, 1600000],
    demandLevel: DemandLevel.HIGH,
    difficulty: CareerDifficulty.ADVANCED,
    workLifeBalance: 2,
    growthPotential: 4,
    governmentOpportunity: 4,
    remoteWorkPotential: 1,
    entranceExams: ["Medical entrance examinations; verify current official eligibility and syllabus"],
    certifications: ["Clinical and specialty credentials; verify current regulatory requirements"],
    recommendedCourses: ["Biology", "Chemistry", "Clinical communication", "Ethics"],
    progression: ["Medical Student", "Resident or Junior Doctor", "Specialist", "Clinical or Academic Leader"],
    relatedCareers: ["pharmacist", "psychologist", "research-scientist"],
    skills: [
      { slug: "clinical-reasoning", name: "Clinical Reasoning", targetLevel: 90, importance: 95 },
      { slug: "biology", name: "Biology", targetLevel: 90, importance: 90, isTechnical: true },
      { slug: "empathy", name: "Empathy", targetLevel: 85, importance: 85 },
      { slug: "communication", name: "Communication", targetLevel: 80, importance: 80 },
    ],
    fit: {
      interestTargets: { healthcare: 95, science: 95, socialService: 85, research: 65 },
      personalityTargets: { empathy: 95, resilience: 85, analyticalThinking: 85, collaboration: 80 },
      valueTargets: { socialImpact: 95, intellectualChallenge: 85, jobSecurity: 70 },
      workPreferenceTargets: { peopleVsSystems: 95, analyticalVsCreative: 35, remoteHybridPreference: 5 },
      academicProfile: { minimumEducationLevel: "CLASS_12", preferredStreams: ["science", "biology"] },
    },
  },
  {
    slug: "pharmacist",
    name: "Pharmacist",
    category: "healthcare",
    overview: "Pharmacists support safe and effective use of medicines across community, hospital, industry, and regulatory settings.",
    whatProfessionalsDo: "They review prescriptions, counsel people where appropriate, manage medicine information, and support quality and safety processes.",
    whyChoose: "Potentially suitable for people who value science, health, accuracy, and helping people make informed care decisions.",
    educationSummary: "Pharmacy education and registration expectations are regulated; consult current approved institution and regulator information.",
    salary: [350000, 800000],
    demandLevel: DemandLevel.MODERATE,
    difficulty: CareerDifficulty.MODERATE,
    workLifeBalance: 3,
    growthPotential: 3,
    governmentOpportunity: 3,
    remoteWorkPotential: 1,
    entranceExams: ["Institution-specific pharmacy admissions"],
    certifications: ["Pharmacovigilance or clinical research foundations"],
    recommendedCourses: ["Chemistry", "Pharmacology", "Patient communication", "Quality systems"],
    progression: ["Pharmacy Student", "Pharmacist", "Senior Pharmacist", "Clinical, Industry, or Regulatory Specialist"],
    relatedCareers: ["doctor", "research-scientist", "psychologist"],
    skills: [
      { slug: "pharmacology", name: "Pharmacology", targetLevel: 80, importance: 90, isTechnical: true },
      { slug: "chemistry", name: "Chemistry", targetLevel: 75, importance: 80, isTechnical: true },
      { slug: "attention-to-detail", name: "Attention to Detail", targetLevel: 85, importance: 85 },
      { slug: "communication", name: "Communication", targetLevel: 70, importance: 70 },
    ],
    fit: {
      interestTargets: { healthcare: 90, science: 90, socialService: 70 },
      personalityTargets: { structurePreference: 80, empathy: 70, analyticalThinking: 75 },
      valueTargets: { socialImpact: 80, jobSecurity: 65, intellectualChallenge: 65 },
      workPreferenceTargets: { peopleVsSystems: 65, analyticalVsCreative: 30, remoteHybridPreference: 10 },
      academicProfile: { minimumEducationLevel: "CLASS_12", preferredStreams: ["science", "biology"] },
    },
  },
  {
    slug: "mechanical-engineer",
    name: "Mechanical Engineer",
    category: "engineering",
    overview: "Mechanical engineers design, test, improve, and maintain machines, products, and industrial systems.",
    whatProfessionalsDo: "They apply engineering principles to design components, analyse performance, collaborate on manufacturing, and solve technical problems.",
    whyChoose: "Worth exploring for people who enjoy physics, practical systems, design constraints, and seeing how things work.",
    educationSummary: "Commonly pursued through a mechanical engineering degree or diploma with internships, lab work, and project experience.",
    salary: [400000, 900000],
    demandLevel: DemandLevel.MODERATE,
    difficulty: CareerDifficulty.ADVANCED,
    workLifeBalance: 3,
    growthPotential: 3,
    governmentOpportunity: 3,
    remoteWorkPotential: 1,
    entranceExams: ["Engineering admissions; verify current institution requirements"],
    certifications: ["CAD foundations", "Quality or safety foundations"],
    recommendedCourses: ["Mechanics", "Thermodynamics", "CAD", "Manufacturing"],
    progression: ["Graduate Engineer", "Mechanical Engineer", "Senior Engineer", "Engineering Manager"],
    relatedCareers: ["civil-engineer", "electrical-engineer", "architect"],
    skills: [
      { slug: "mechanics", name: "Mechanics", targetLevel: 85, importance: 90, isTechnical: true },
      { slug: "cad", name: "CAD", targetLevel: 75, importance: 80, isTechnical: true },
      { slug: "physics", name: "Physics", targetLevel: 80, importance: 80, isTechnical: true },
      { slug: "problem-solving", name: "Problem Solving", targetLevel: 75, importance: 75 },
    ],
    fit: {
      interestTargets: { engineering: 95, mathematics: 75, science: 80, technology: 60 },
      personalityTargets: { analyticalThinking: 85, structurePreference: 75, creativity: 60 },
      valueTargets: { intellectualChallenge: 75, jobSecurity: 65, growth: 65 },
      workPreferenceTargets: { peopleVsSystems: 30, analyticalVsCreative: 35, remoteHybridPreference: 15 },
      academicProfile: { minimumEducationLevel: "UNDERGRADUATE", preferredStreams: ["science", "engineering"] },
    },
  },
  {
    slug: "civil-engineer",
    name: "Civil Engineer",
    category: "engineering",
    overview: "Civil engineers plan, design, and help deliver infrastructure such as buildings, transport, water, and public works.",
    whatProfessionalsDo: "They analyse requirements, prepare designs, coordinate with stakeholders, support site work, and apply safety and quality standards.",
    whyChoose: "Potentially suitable for people who like applied maths, tangible projects, planning, and improving communities.",
    educationSummary: "Usually pursued through civil engineering education with site exposure, software practice, and current local regulatory awareness.",
    salary: [400000, 900000],
    demandLevel: DemandLevel.MODERATE,
    difficulty: CareerDifficulty.ADVANCED,
    workLifeBalance: 3,
    growthPotential: 3,
    governmentOpportunity: 4,
    remoteWorkPotential: 1,
    entranceExams: ["Engineering admissions; verify current institution requirements"],
    certifications: ["Project management foundations", "Construction safety foundations"],
    recommendedCourses: ["Structural analysis", "Surveying", "Construction management", "CAD"],
    progression: ["Graduate Engineer", "Civil Engineer", "Project Engineer", "Project or Design Lead"],
    relatedCareers: ["mechanical-engineer", "architect", "government-officer"],
    skills: [
      { slug: "structural-analysis", name: "Structural Analysis", targetLevel: 80, importance: 85, isTechnical: true },
      { slug: "cad", name: "CAD", targetLevel: 70, importance: 70, isTechnical: true },
      { slug: "project-management", name: "Project Management", targetLevel: 70, importance: 75 },
      { slug: "mathematics", name: "Mathematics", targetLevel: 75, importance: 75, isTechnical: true },
    ],
    fit: {
      interestTargets: { engineering: 95, mathematics: 80, publicAdministration: 55, design: 55 },
      personalityTargets: { structurePreference: 85, analyticalThinking: 80, collaboration: 70 },
      valueTargets: { socialImpact: 70, jobSecurity: 65, intellectualChallenge: 70 },
      workPreferenceTargets: { peopleVsSystems: 50, analyticalVsCreative: 35, governmentVsPrivate: 60, remoteHybridPreference: 10 },
      academicProfile: { minimumEducationLevel: "UNDERGRADUATE", preferredStreams: ["science", "engineering"] },
    },
  },
  {
    slug: "electrical-engineer",
    name: "Electrical Engineer",
    category: "engineering",
    overview: "Electrical engineers work with power, control, electronics, and electrical systems in many sectors.",
    whatProfessionalsDo: "They design and test systems, analyse performance, work with safety standards, and solve equipment or infrastructure problems.",
    whyChoose: "A potentially fitting path for people who enjoy physics, maths, systems, and solving practical technical problems.",
    educationSummary: "Common routes include electrical engineering education plus laboratories, projects, industry exposure, and software tools.",
    salary: [450000, 950000],
    demandLevel: DemandLevel.MODERATE,
    difficulty: CareerDifficulty.ADVANCED,
    workLifeBalance: 3,
    growthPotential: 3,
    governmentOpportunity: 4,
    remoteWorkPotential: 1,
    entranceExams: ["Engineering admissions; verify current institution requirements"],
    certifications: ["Electrical safety foundations", "Control systems foundations"],
    recommendedCourses: ["Circuit theory", "Power systems", "Control systems", "Embedded fundamentals"],
    progression: ["Graduate Engineer", "Electrical Engineer", "Senior Engineer", "Technical Lead"],
    relatedCareers: ["electronics-engineer", "mechanical-engineer", "government-officer"],
    skills: [
      { slug: "circuit-analysis", name: "Circuit Analysis", targetLevel: 85, importance: 90, isTechnical: true },
      { slug: "power-systems", name: "Power Systems", targetLevel: 75, importance: 80, isTechnical: true },
      { slug: "physics", name: "Physics", targetLevel: 80, importance: 80, isTechnical: true },
      { slug: "problem-solving", name: "Problem Solving", targetLevel: 75, importance: 75 },
    ],
    fit: {
      interestTargets: { engineering: 95, mathematics: 80, science: 85, technology: 65 },
      personalityTargets: { analyticalThinking: 90, structurePreference: 80, independence: 65 },
      valueTargets: { intellectualChallenge: 75, jobSecurity: 70, growth: 65 },
      workPreferenceTargets: { peopleVsSystems: 30, analyticalVsCreative: 25, remoteHybridPreference: 10 },
      academicProfile: { minimumEducationLevel: "UNDERGRADUATE", preferredStreams: ["science", "engineering"] },
    },
  },
  {
    slug: "electronics-engineer",
    name: "Electronics Engineer",
    category: "engineering",
    overview: "Electronics engineers design and test circuits, devices, embedded systems, and communication-related technologies.",
    whatProfessionalsDo: "They work with components, hardware, embedded code, testing equipment, and multidisciplinary product teams.",
    whyChoose: "Worth exploring for people who enjoy technology, physics, detailed experimentation, and turning ideas into working devices.",
    educationSummary: "Usually pursued through electronics, electrical, or related engineering education supported by projects and lab practice.",
    salary: [450000, 1000000],
    demandLevel: DemandLevel.MODERATE,
    difficulty: CareerDifficulty.ADVANCED,
    workLifeBalance: 3,
    growthPotential: 4,
    governmentOpportunity: 3,
    remoteWorkPotential: 2,
    entranceExams: ["Engineering admissions; verify current institution requirements"],
    certifications: ["Embedded systems foundations", "PCB design foundations"],
    recommendedCourses: ["Electronics", "Embedded systems", "Signals", "PCB design"],
    progression: ["Graduate Engineer", "Electronics Engineer", "Senior Engineer", "Systems or Hardware Lead"],
    relatedCareers: ["electrical-engineer", "software-engineer", "research-scientist"],
    skills: [
      { slug: "electronics", name: "Electronics", targetLevel: 85, importance: 90, isTechnical: true },
      { slug: "embedded-systems", name: "Embedded Systems", targetLevel: 75, importance: 80, isTechnical: true },
      { slug: "circuit-analysis", name: "Circuit Analysis", targetLevel: 75, importance: 75, isTechnical: true },
      { slug: "testing", name: "Testing", targetLevel: 70, importance: 65, isTechnical: true },
    ],
    fit: {
      interestTargets: { engineering: 95, technology: 85, science: 80, mathematics: 70 },
      personalityTargets: { analyticalThinking: 90, structurePreference: 75, creativity: 60 },
      valueTargets: { intellectualChallenge: 80, growth: 70, jobSecurity: 60 },
      workPreferenceTargets: { peopleVsSystems: 25, analyticalVsCreative: 30, remoteHybridPreference: 20 },
      academicProfile: { minimumEducationLevel: "UNDERGRADUATE", preferredStreams: ["science", "engineering"] },
    },
  },
  {
    slug: "teacher",
    name: "Teacher",
    category: "education",
    overview: "Teachers design learning experiences, explain concepts, assess progress, and support students' development.",
    whatProfessionalsDo: "They prepare lessons, facilitate learning, provide feedback, collaborate with families or colleagues, and continue professional development.",
    whyChoose: "A meaningful path for people who enjoy communication, subject knowledge, patience, and helping others grow.",
    educationSummary: "Qualifications and licensing expectations vary by education level and institution; check current official and employer requirements.",
    salary: [300000, 750000],
    demandLevel: DemandLevel.MODERATE,
    difficulty: CareerDifficulty.MODERATE,
    workLifeBalance: 4,
    growthPotential: 3,
    governmentOpportunity: 4,
    remoteWorkPotential: 2,
    entranceExams: ["Institution or state-specific education recruitment processes; verify current rules"],
    certifications: ["Teaching and learning foundations", "Inclusive education foundations"],
    recommendedCourses: ["Pedagogy", "Subject specialisation", "Assessment", "Communication"],
    progression: ["Teacher Trainee", "Teacher", "Senior Teacher", "Academic Coordinator or School Leader"],
    relatedCareers: ["professor", "psychologist", "government-officer"],
    skills: [
      { slug: "teaching", name: "Teaching", targetLevel: 85, importance: 95 },
      { slug: "communication", name: "Communication", targetLevel: 85, importance: 85 },
      { slug: "empathy", name: "Empathy", targetLevel: 80, importance: 80 },
      { slug: "organisation", name: "Organisation", targetLevel: 70, importance: 70 },
    ],
    fit: {
      interestTargets: { education: 95, communication: 85, socialService: 85, research: 55 },
      personalityTargets: { empathy: 90, collaboration: 80, structurePreference: 70, leadership: 60 },
      valueTargets: { socialImpact: 95, workLifeBalance: 70, jobSecurity: 65 },
      workPreferenceTargets: { peopleVsSystems: 95, analyticalVsCreative: 55, governmentVsPrivate: 60, remoteHybridPreference: 20 },
      academicProfile: { minimumEducationLevel: "UNDERGRADUATE" },
    },
  },
  {
    slug: "professor",
    name: "Professor",
    category: "education",
    overview: "Professors teach advanced learners, develop curricula, mentor students, and may conduct research and service work.",
    whatProfessionalsDo: "They teach, supervise projects, assess learning, write or review research, and contribute to their institution's academic community.",
    whyChoose: "Potentially suitable for people who enjoy deep subject expertise, teaching, research, and long-term intellectual work.",
    educationSummary: "Academic roles often require advanced qualifications and institution-specific criteria; verify current expectations with the relevant institution.",
    salary: [500000, 1200000],
    demandLevel: DemandLevel.MODERATE,
    difficulty: CareerDifficulty.ADVANCED,
    workLifeBalance: 4,
    growthPotential: 4,
    governmentOpportunity: 4,
    remoteWorkPotential: 2,
    entranceExams: ["Postgraduate or doctoral admissions; verify current institution requirements"],
    certifications: ["Teaching and research ethics foundations"],
    recommendedCourses: ["Research methods", "Pedagogy", "Academic writing", "Subject specialisation"],
    progression: ["Research Student", "Lecturer or Assistant Professor", "Professor", "Academic Leader"],
    relatedCareers: ["teacher", "research-scientist", "psychologist"],
    skills: [
      { slug: "teaching", name: "Teaching", targetLevel: 85, importance: 85 },
      { slug: "research-methods", name: "Research Methods", targetLevel: 85, importance: 90 },
      { slug: "academic-writing", name: "Academic Writing", targetLevel: 80, importance: 80 },
      { slug: "mentoring", name: "Mentoring", targetLevel: 75, importance: 70 },
    ],
    fit: {
      interestTargets: { education: 90, research: 95, writing: 75, science: 60 },
      personalityTargets: { analyticalThinking: 80, independence: 80, collaboration: 65 },
      valueTargets: { intellectualChallenge: 95, socialImpact: 75, independence: 70 },
      workPreferenceTargets: { peopleVsSystems: 65, analyticalVsCreative: 45, governmentVsPrivate: 60, remoteHybridPreference: 35 },
      academicProfile: { minimumEducationLevel: "POSTGRADUATE" },
    },
  },
  {
    slug: "research-scientist",
    name: "Research Scientist",
    category: "research",
    overview: "Research scientists formulate questions, design studies, analyse evidence, and communicate reliable findings.",
    whatProfessionalsDo: "They review literature, conduct experiments or analyses, document methods, collaborate with peers, and interpret uncertainty.",
    whyChoose: "A potentially fitting path for people who enjoy curiosity, rigour, experimentation, and contributing new knowledge.",
    educationSummary: "Many research roles need advanced subject training; exact requirements differ greatly across domains and employers.",
    salary: [500000, 1200000],
    demandLevel: DemandLevel.MODERATE,
    difficulty: CareerDifficulty.ADVANCED,
    workLifeBalance: 3,
    growthPotential: 4,
    governmentOpportunity: 4,
    remoteWorkPotential: 2,
    entranceExams: ["Postgraduate or research admissions; verify current institution requirements"],
    certifications: ["Research ethics foundations", "Data analysis foundations"],
    recommendedCourses: ["Research methods", "Statistics", "Scientific writing", "Domain specialisation"],
    progression: ["Research Assistant", "Research Scientist", "Senior Scientist", "Principal Investigator or R&D Lead"],
    relatedCareers: ["data-scientist", "professor", "doctor"],
    skills: [
      { slug: "research-methods", name: "Research Methods", targetLevel: 90, importance: 95 },
      { slug: "statistics", name: "Statistics", targetLevel: 75, importance: 75, isTechnical: true },
      { slug: "scientific-writing", name: "Scientific Writing", targetLevel: 80, importance: 80 },
      { slug: "critical-thinking", name: "Critical Thinking", targetLevel: 85, importance: 85 },
    ],
    fit: {
      interestTargets: { research: 100, science: 90, mathematics: 65, writing: 65 },
      personalityTargets: { analyticalThinking: 95, independence: 85, curiosity: 90 },
      valueTargets: { intellectualChallenge: 100, socialImpact: 65, independence: 75 },
      workPreferenceTargets: { peopleVsSystems: 35, analyticalVsCreative: 30, remoteHybridPreference: 45 },
      academicProfile: { minimumEducationLevel: "POSTGRADUATE", preferredStreams: ["science", "engineering", "medicine", "social science"] },
    },
  },
  {
    slug: "entrepreneur",
    name: "Entrepreneur",
    category: "entrepreneurship",
    overview: "Entrepreneurs identify problems, test solutions, build teams or products, and make decisions under uncertainty.",
    whatProfessionalsDo: "They learn from customers, shape a business model, manage resources, communicate a vision, and adapt to changing conditions.",
    whyChoose: "Worth exploring for people who value ownership, creativity, persistence, leadership, and solving real-world problems.",
    educationSummary: "There is no single required degree. Relevant knowledge, networks, practical experience, and responsible financial planning all matter.",
    salary: [0, 1500000],
    demandLevel: DemandLevel.MODERATE,
    difficulty: CareerDifficulty.ADVANCED,
    workLifeBalance: 2,
    growthPotential: 5,
    governmentOpportunity: 1,
    remoteWorkPotential: 3,
    entranceExams: ["None required; programmes and incubators have their own criteria"],
    certifications: ["Entrepreneurship foundations", "Financial literacy foundations"],
    recommendedCourses: ["Problem discovery", "Business models", "Finance basics", "Leadership"],
    progression: ["Idea Validation", "Early Venture", "Growth Stage", "Founder or Venture Leader"],
    relatedCareers: ["product-manager", "digital-marketer", "investment-banker"],
    skills: [
      { slug: "opportunity-analysis", name: "Opportunity Analysis", targetLevel: 75, importance: 80 },
      { slug: "leadership", name: "Leadership", targetLevel: 80, importance: 90 },
      { slug: "financial-literacy", name: "Financial Literacy", targetLevel: 70, importance: 75 },
      { slug: "resilience", name: "Resilience", targetLevel: 85, importance: 90 },
    ],
    fit: {
      interestTargets: { entrepreneurship: 100, business: 90, leadership: 90, creativity: 75 },
      personalityTargets: { riskTolerance: 90, leadership: 90, independence: 95, resilience: 90 },
      valueTargets: { independence: 95, growth: 95, intellectualChallenge: 80 },
      workPreferenceTargets: { peopleVsSystems: 70, analyticalVsCreative: 60, stabilityVsFlexibility: 90, remoteHybridPreference: 55 },
      academicProfile: {},
    },
  },
  {
    slug: "digital-marketer",
    name: "Digital Marketer",
    category: "media",
    overview: "Digital marketers plan, create, distribute, and measure communication that helps organisations reach relevant audiences.",
    whatProfessionalsDo: "They work on campaigns, content, search, social channels, performance data, and collaboration with creative and business teams.",
    whyChoose: "Potentially suitable for people who enjoy creativity, audience insight, experimentation, and using data to improve communication.",
    educationSummary: "Routes include marketing, communications, business, design, self-directed projects, and portfolio evidence.",
    salary: [300000, 800000],
    demandLevel: DemandLevel.HIGH,
    difficulty: CareerDifficulty.MODERATE,
    workLifeBalance: 3,
    growthPotential: 4,
    governmentOpportunity: 1,
    remoteWorkPotential: 4,
    entranceExams: ["Institution-specific marketing or communication admissions"],
    certifications: ["Digital marketing foundations", "Analytics foundations"],
    recommendedCourses: ["Content strategy", "Search marketing", "Analytics", "Campaign planning"],
    progression: ["Marketing Associate", "Digital Marketer", "Marketing Manager", "Growth or Brand Lead"],
    relatedCareers: ["content-creator", "product-manager", "ui-ux-designer"],
    skills: [
      { slug: "content-strategy", name: "Content Strategy", targetLevel: 75, importance: 80 },
      { slug: "marketing-analytics", name: "Marketing Analytics", targetLevel: 70, importance: 75, isTechnical: true },
      { slug: "copywriting", name: "Copywriting", targetLevel: 70, importance: 70 },
      { slug: "experimentation", name: "Experimentation", targetLevel: 70, importance: 65 },
    ],
    fit: {
      interestTargets: { media: 90, creativity: 85, business: 75, communication: 90, data: 55 },
      personalityTargets: { creativity: 85, collaboration: 75, curiosity: 75, riskTolerance: 60 },
      valueTargets: { growth: 80, creativity: 80, workLifeBalance: 60 },
      workPreferenceTargets: { peopleVsSystems: 70, analyticalVsCreative: 75, remoteHybridPreference: 75 },
      academicProfile: { minimumEducationLevel: "UNDERGRADUATE", preferredStreams: ["marketing", "business", "communication", "design", "arts"] },
    },
  },
  {
    slug: "content-creator",
    name: "Content Creator",
    category: "media",
    overview: "Content creators plan and produce useful, engaging material for a defined audience across appropriate formats and channels.",
    whatProfessionalsDo: "They research topics, create scripts or assets, publish, analyse audience feedback, and manage consistent creative workflows.",
    whyChoose: "Worth exploring for people who enjoy storytelling, independent creative work, learning about audiences, and building a portfolio.",
    educationSummary: "There is no single required qualification; craft, ethics, portfolio quality, and sustainable business practices are important.",
    salary: [0, 900000],
    demandLevel: DemandLevel.MODERATE,
    difficulty: CareerDifficulty.MODERATE,
    workLifeBalance: 2,
    growthPotential: 4,
    governmentOpportunity: 1,
    remoteWorkPotential: 5,
    entranceExams: ["None required; programmes and employers set their own criteria"],
    certifications: ["Media literacy foundations", "Digital storytelling foundations"],
    recommendedCourses: ["Storytelling", "Video or visual production", "Audience research", "Digital ethics"],
    progression: ["Portfolio Builder", "Independent or In-house Creator", "Senior Creator", "Creative Lead or Studio Founder"],
    relatedCareers: ["digital-marketer", "ui-ux-designer", "entrepreneur"],
    skills: [
      { slug: "storytelling", name: "Storytelling", targetLevel: 85, importance: 90 },
      { slug: "content-production", name: "Content Production", targetLevel: 80, importance: 85, isTechnical: true },
      { slug: "audience-research", name: "Audience Research", targetLevel: 65, importance: 65 },
      { slug: "self-management", name: "Self Management", targetLevel: 75, importance: 75 },
    ],
    fit: {
      interestTargets: { media: 100, creativity: 95, writing: 80, communication: 90, entrepreneurship: 65 },
      personalityTargets: { creativity: 95, independence: 90, riskTolerance: 65, curiosity: 80 },
      valueTargets: { independence: 90, creativity: 95, growth: 70 },
      workPreferenceTargets: { peopleVsSystems: 65, analyticalVsCreative: 90, stabilityVsFlexibility: 85, remoteHybridPreference: 95 },
      academicProfile: {},
    },
  },
  {
    slug: "architect",
    name: "Architect",
    category: "design",
    overview: "Architects design spaces and coordinate the technical, functional, social, and aesthetic aspects of built environments.",
    whatProfessionalsDo: "They develop concepts, produce drawings, coordinate with engineers and clients, and consider safety, regulations, and construction constraints.",
    whyChoose: "Potentially suitable for people who combine visual creativity with technical reasoning, planning, and interest in how people use spaces.",
    educationSummary: "Architecture education and professional practice requirements are regulated and should be confirmed through current official sources.",
    salary: [400000, 1000000],
    demandLevel: DemandLevel.MODERATE,
    difficulty: CareerDifficulty.ADVANCED,
    workLifeBalance: 3,
    growthPotential: 4,
    governmentOpportunity: 2,
    remoteWorkPotential: 2,
    entranceExams: ["Architecture admissions; verify current official and institution requirements"],
    certifications: ["Sustainable design foundations", "Building information modelling foundations"],
    recommendedCourses: ["Design studio", "Architectural history", "CAD or BIM", "Construction systems"],
    progression: ["Architecture Student", "Junior Architect", "Architect", "Project or Design Lead"],
    relatedCareers: ["civil-engineer", "ui-ux-designer", "mechanical-engineer"],
    skills: [
      { slug: "architectural-design", name: "Architectural Design", targetLevel: 85, importance: 95 },
      { slug: "cad", name: "CAD", targetLevel: 80, importance: 80, isTechnical: true },
      { slug: "spatial-reasoning", name: "Spatial Reasoning", targetLevel: 80, importance: 85 },
      { slug: "project-management", name: "Project Management", targetLevel: 65, importance: 65 },
    ],
    fit: {
      interestTargets: { design: 100, creativity: 95, engineering: 65, mathematics: 60 },
      personalityTargets: { creativity: 95, structurePreference: 65, collaboration: 70 },
      valueTargets: { creativity: 95, intellectualChallenge: 75, socialImpact: 60 },
      workPreferenceTargets: { peopleVsSystems: 55, analyticalVsCreative: 80, remoteHybridPreference: 30 },
      academicProfile: { minimumEducationLevel: "UNDERGRADUATE", preferredStreams: ["science", "arts", "design"] },
    },
  },
  {
    slug: "psychologist",
    name: "Psychologist",
    category: "healthcare",
    overview: "Psychologists apply evidence-based understanding of behaviour and mental processes in clinical, educational, research, or organisational settings.",
    whatProfessionalsDo: "They may assess needs, support interventions within their scope, conduct research, communicate findings, and collaborate with care or education teams.",
    whyChoose: "Potentially suitable for people interested in human behaviour, empathy, careful listening, research, and ethical practice.",
    educationSummary: "Specialisation, licensing, and scope-of-practice rules vary by role and location; check current official requirements before choosing a pathway.",
    salary: [350000, 900000],
    demandLevel: DemandLevel.MODERATE,
    difficulty: CareerDifficulty.ADVANCED,
    workLifeBalance: 3,
    growthPotential: 4,
    governmentOpportunity: 3,
    remoteWorkPotential: 2,
    entranceExams: ["Institution-specific psychology admissions; verify current official requirements"],
    certifications: ["Counselling skills foundations", "Research ethics foundations"],
    recommendedCourses: ["Psychology", "Research methods", "Ethics", "Communication"],
    progression: ["Psychology Student", "Assistant or Trainee Role", "Psychologist", "Specialist or Practice Lead"],
    relatedCareers: ["teacher", "doctor", "research-scientist"],
    skills: [
      { slug: "psychology", name: "Psychology", targetLevel: 85, importance: 90 },
      { slug: "empathy", name: "Empathy", targetLevel: 90, importance: 90 },
      { slug: "active-listening", name: "Active Listening", targetLevel: 85, importance: 85 },
      { slug: "research-methods", name: "Research Methods", targetLevel: 70, importance: 70 },
    ],
    fit: {
      interestTargets: { healthcare: 85, socialService: 95, research: 70, communication: 80 },
      personalityTargets: { empathy: 100, analyticalThinking: 70, patience: 85, collaboration: 70 },
      valueTargets: { socialImpact: 95, intellectualChallenge: 70, workLifeBalance: 60 },
      workPreferenceTargets: { peopleVsSystems: 95, analyticalVsCreative: 55, remoteHybridPreference: 25 },
      academicProfile: { minimumEducationLevel: "POSTGRADUATE", preferredStreams: ["psychology", "science", "arts"] },
    },
  },
  {
    slug: "government-officer",
    name: "Government Officer",
    category: "government",
    overview: "Government officers support administration, programmes, citizen services, regulation, and implementation in public institutions.",
    whatProfessionalsDo: "Responsibilities differ by department and may include documentation, coordination, service delivery, analysis, and public communication.",
    whyChoose: "Worth exploring for people who value public service, stable institutional work, organisation, and helping programmes function well.",
    educationSummary: "Recruitment routes, eligibility, and examinations differ by agency and can change; use current official notifications to plan.",
    salary: [350000, 850000],
    demandLevel: DemandLevel.MODERATE,
    difficulty: CareerDifficulty.MODERATE,
    workLifeBalance: 4,
    growthPotential: 3,
    governmentOpportunity: 5,
    remoteWorkPotential: 1,
    entranceExams: ["SSC, state recruitment, banking, or department processes; verify current official notifications"],
    certifications: ["Public administration foundations", "Office productivity foundations"],
    recommendedCourses: ["General studies", "Reasoning", "Public administration", "Communication"],
    progression: ["Entry-Level Officer", "Section or Programme Officer", "Senior Officer", "Departmental Leadership"],
    relatedCareers: ["civil-services-officer", "indian-police-service-officer", "teacher"],
    skills: [
      { slug: "organisation", name: "Organisation", targetLevel: 80, importance: 85 },
      { slug: "public-administration", name: "Public Administration", targetLevel: 70, importance: 75 },
      { slug: "communication", name: "Communication", targetLevel: 70, importance: 70 },
      { slug: "attention-to-detail", name: "Attention to Detail", targetLevel: 75, importance: 75 },
    ],
    fit: {
      interestTargets: { publicAdministration: 90, socialService: 75, communication: 60, organisation: 80 },
      personalityTargets: { structurePreference: 90, stabilityPreference: 80, collaboration: 65 },
      valueTargets: { jobSecurity: 90, socialImpact: 75, workLifeBalance: 70 },
      workPreferenceTargets: { peopleVsSystems: 65, analyticalVsCreative: 40, governmentVsPrivate: 100, remoteHybridPreference: 10 },
      academicProfile: { minimumEducationLevel: "CLASS_12" },
    },
  },
  {
    slug: "banking-officer",
    name: "Banking Officer",
    category: "finance",
    overview: "Banking officers support customer service, operations, compliance, lending, and financial products within regulated institutions.",
    whatProfessionalsDo: "Work can involve customer guidance, documentation, financial review, operational controls, and team coordination.",
    whyChoose: "Potentially suitable for people who value finance, structured work, customer interaction, and institutional responsibility.",
    educationSummary: "Recruitment and eligibility vary by bank and year; always confirm current requirements through official recruitment notices.",
    salary: [400000, 900000],
    demandLevel: DemandLevel.MODERATE,
    difficulty: CareerDifficulty.MODERATE,
    workLifeBalance: 3,
    growthPotential: 3,
    governmentOpportunity: 4,
    remoteWorkPotential: 1,
    entranceExams: ["Bank recruitment examinations; verify current official eligibility and syllabus"],
    certifications: ["Banking and finance foundations", "Customer service foundations"],
    recommendedCourses: ["Quantitative aptitude", "Financial services", "Reasoning", "Communication"],
    progression: ["Officer Trainee", "Banking Officer", "Manager", "Senior Banking or Operations Leader"],
    relatedCareers: ["financial-analyst", "government-officer", "chartered-accountant"],
    skills: [
      { slug: "financial-literacy", name: "Financial Literacy", targetLevel: 75, importance: 80 },
      { slug: "customer-service", name: "Customer Service", targetLevel: 75, importance: 75 },
      { slug: "numeracy", name: "Numeracy", targetLevel: 75, importance: 75 },
      { slug: "attention-to-detail", name: "Attention to Detail", targetLevel: 75, importance: 75 },
    ],
    fit: {
      interestTargets: { finance: 85, business: 65, communication: 60, mathematics: 65 },
      personalityTargets: { structurePreference: 85, stabilityPreference: 85, collaboration: 65 },
      valueTargets: { jobSecurity: 90, workLifeBalance: 60, socialImpact: 55 },
      workPreferenceTargets: { peopleVsSystems: 70, analyticalVsCreative: 30, governmentVsPrivate: 70, remoteHybridPreference: 10 },
      academicProfile: { minimumEducationLevel: "GRADUATE", preferredStreams: ["commerce", "business", "economics", "mathematics"] },
    },
  },
  {
    slug: "defence-officer",
    name: "Defence Officer",
    category: "government",
    overview: "Defence officers lead teams and support national security, operations, logistics, training, and administration in a disciplined environment.",
    whatProfessionalsDo: "Responsibilities vary by service and role, but can include leadership, planning, training, coordination, and operational readiness.",
    whyChoose: "A demanding path for people who value service, leadership, teamwork, discipline, and physical or operational readiness.",
    educationSummary: "Selection and medical, academic, and age criteria are governed by official notices that can change; verify the current process directly.",
    salary: [600000, 1300000],
    demandLevel: DemandLevel.MODERATE,
    difficulty: CareerDifficulty.ADVANCED,
    workLifeBalance: 2,
    growthPotential: 4,
    governmentOpportunity: 5,
    remoteWorkPotential: 1,
    entranceExams: ["Defence recruitment examinations and selection processes; verify current official notices"],
    certifications: ["Leadership and fitness learning"],
    recommendedCourses: ["General studies", "Leadership", "Physical fitness", "Communication"],
    progression: ["Cadet or Trainee", "Officer", "Senior Officer", "Command or Staff Leadership"],
    relatedCareers: ["indian-police-service-officer", "civil-services-officer", "government-officer"],
    skills: [
      { slug: "leadership", name: "Leadership", targetLevel: 85, importance: 90 },
      { slug: "teamwork", name: "Teamwork", targetLevel: 85, importance: 85 },
      { slug: "resilience", name: "Resilience", targetLevel: 90, importance: 90 },
      { slug: "decision-making", name: "Decision Making", targetLevel: 75, importance: 75 },
    ],
    fit: {
      interestTargets: { publicAdministration: 75, socialService: 85, leadership: 95, engineering: 55 },
      personalityTargets: { leadership: 95, resilience: 95, collaboration: 85, structurePreference: 80 },
      valueTargets: { socialImpact: 90, jobSecurity: 70, prestige: 70 },
      workPreferenceTargets: { peopleVsSystems: 80, analyticalVsCreative: 40, governmentVsPrivate: 100, remoteHybridPreference: 5 },
      academicProfile: { minimumEducationLevel: "CLASS_12" },
    },
  },
];

const SCALE_OPTIONS = [
  { value: 1, label: "Not at all like me" },
  { value: 2, label: "Slightly like me" },
  { value: 3, label: "Somewhat like me" },
  { value: 4, label: "Mostly like me" },
  { value: 5, label: "Very much like me" },
];

const QUESTION_PROMPTS: Array<{
  slug: string;
  dimension: AssessmentDimension;
  prompt: string;
  helperText: string;
}> = [
  ["interest-realistic", AssessmentDimension.INTEREST, "I enjoy building, repairing, or working with practical systems.", "Hands-on and technical interests."],
  ["interest-investigative", AssessmentDimension.INTEREST, "I enjoy investigating questions and finding evidence before deciding.", "Curiosity and research interests."],
  ["interest-artistic", AssessmentDimension.INTEREST, "I enjoy creating original ideas, stories, visuals, or experiences.", "Creative interests."],
  ["interest-social", AssessmentDimension.INTEREST, "I feel energised when I help, teach, or support other people.", "People-centred interests."],
  ["interest-enterprising", AssessmentDimension.INTEREST, "I enjoy persuading, organising, or leading others toward a goal.", "Leadership and business interests."],
  ["interest-conventional", AssessmentDimension.INTEREST, "I like bringing order to information, plans, and processes.", "Structure and organisation interests."],
  ["skill-analytical-thinking", AssessmentDimension.SKILL, "I can break a complex problem into smaller, manageable parts.", "Analytical thinking."],
  ["skill-mathematics", AssessmentDimension.SKILL, "I feel confident using numbers, patterns, or quantitative reasoning.", "Mathematics and numeracy."],
  ["skill-communication", AssessmentDimension.SKILL, "I can explain my ideas clearly to different kinds of people.", "Communication."],
  ["skill-leadership", AssessmentDimension.SKILL, "I can help a group decide what to do next and move forward.", "Leadership."],
  ["skill-creativity", AssessmentDimension.SKILL, "I often think of more than one way to approach a challenge.", "Creative problem-solving."],
  ["skill-problem-solving", AssessmentDimension.SKILL, "I persist with a difficult problem until I find a useful next step.", "Problem-solving."],
  ["skill-research", AssessmentDimension.SKILL, "I can compare sources and decide which information is dependable.", "Research skills."],
  ["skill-organisation", AssessmentDimension.SKILL, "I can plan tasks and keep track of deadlines or details.", "Organisation."],
  ["skill-technical-aptitude", AssessmentDimension.SKILL, "I learn new digital tools or technical concepts with interest.", "Technical aptitude."],
  ["personality-risk-tolerance", AssessmentDimension.PERSONALITY, "I can stay composed when outcomes are uncertain.", "Comfort with uncertainty."],
  ["personality-collaboration", AssessmentDimension.PERSONALITY, "I prefer solving important problems with other people.", "Collaboration."],
  ["personality-independence", AssessmentDimension.PERSONALITY, "I enjoy owning a task and deciding how to carry it out.", "Independence."],
  ["personality-leadership", AssessmentDimension.PERSONALITY, "I am comfortable taking responsibility when a group needs direction.", "Leadership style."],
  ["personality-structure", AssessmentDimension.PERSONALITY, "I prefer clear expectations, routines, and processes.", "Structure preference."],
  ["personality-creativity", AssessmentDimension.PERSONALITY, "I am energised by open-ended work that needs imagination.", "Creativity preference."],
  ["personality-stability", AssessmentDimension.PERSONALITY, "I prefer predictable work conditions over frequent change.", "Stability preference."],
  ["value-salary", AssessmentDimension.VALUE, "Earning potential is important in my career decisions.", "Career value."],
  ["value-security", AssessmentDimension.VALUE, "Long-term job security is important in my career decisions.", "Career value."],
  ["value-social-impact", AssessmentDimension.VALUE, "Making a positive difference to people or society is important to me.", "Career value."],
  ["value-prestige", AssessmentDimension.VALUE, "Professional recognition or status is important to me.", "Career value."],
  ["value-work-life-balance", AssessmentDimension.VALUE, "Having time and energy outside work is important to me.", "Career value."],
  ["value-growth", AssessmentDimension.VALUE, "Frequent learning and advancement opportunities are important to me.", "Career value."],
  ["value-intellectual-challenge", AssessmentDimension.VALUE, "I want work that regularly stretches my thinking.", "Career value."],
  ["value-independence", AssessmentDimension.VALUE, "I value having autonomy over how I work.", "Career value."],
  ["preference-people-systems", AssessmentDimension.WORK_PREFERENCE, "I prefer work that involves regular interaction with people.", "People versus systems preference."],
  ["preference-analytical-creative", AssessmentDimension.WORK_PREFERENCE, "I prefer analytical work over primarily creative work.", "Analytical versus creative preference."],
  ["preference-stability-flexibility", AssessmentDimension.WORK_PREFERENCE, "I prefer flexibility and variety over a highly predictable routine.", "Stability versus flexibility preference."],
  ["preference-government-private", AssessmentDimension.WORK_PREFERENCE, "I am drawn to public-sector or government-oriented work.", "Government versus private-sector preference."],
  ["preference-remote-hybrid", AssessmentDimension.WORK_PREFERENCE, "Remote or hybrid work is important to me.", "Work-location preference."],
];

function labelFromSlug(slug: string): string {
  return slug
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function createRoadmap(career: CareerSeed) {
  const [firstSkill, secondSkill, thirdSkill] = career.skills;
  const first = firstSkill?.name ?? "Core Foundations";
  const second = secondSkill?.name ?? "Core Practice";
  const third = thirdSkill?.name ?? "Applied Skills";

  return [
    {
      title: "Foundation",
      description: `Build the core knowledge that supports ${career.name}.`,
      items: [
        { title: `Learn ${first}`, description: "Use a beginner-friendly course or structured learning plan.", itemType: RoadmapItemType.LEARNING, estimatedHours: 20 },
        { title: `Practice ${second}`, description: "Complete short exercises and record what you learn.", itemType: RoadmapItemType.LEARNING, estimatedHours: 20 },
      ],
    },
    {
      title: "Core Skills",
      description: "Turn foundational knowledge into repeatable skills.",
      items: [
        { title: `Develop ${third}`, description: "Work through progressively more realistic exercises.", itemType: RoadmapItemType.LEARNING, estimatedHours: 24 },
        { title: "Study current pathway requirements", description: "Use official institution, regulator, or employer sources because requirements can change.", itemType: RoadmapItemType.LEARNING, estimatedHours: 4 },
      ],
    },
    {
      title: "Applied Practice",
      description: "Build evidence of your interest and ability.",
      items: [
        { title: `Complete a ${career.name} practice project`, description: "Choose a small, ethical project that demonstrates a relevant skill.", itemType: RoadmapItemType.PROJECT, estimatedHours: 30 },
        { title: "Seek feedback", description: "Ask a teacher, mentor, or practitioner for specific feedback on your work.", itemType: RoadmapItemType.PROJECT, estimatedHours: 4 },
      ],
    },
    {
      title: "Credentials & Exposure",
      description: "Explore courses, certifications, and real-world exposure appropriate to your stage.",
      items: [
        { title: "Review relevant certification options", description: "Compare current official course or credential information before investing time or money.", itemType: RoadmapItemType.CERTIFICATION, estimatedHours: 3 },
        { title: "Explore a real-world perspective", description: "Attend a career talk, informational interview, or supervised observation when appropriate.", itemType: RoadmapItemType.PROJECT, estimatedHours: 4 },
      ],
    },
    {
      title: "Career Preparation",
      description: "Prepare a clear next step while keeping this path open to review.",
      items: [
        { title: "Update your portfolio or résumé", description: "Describe learning and projects truthfully, with clear examples of your contribution.", itemType: RoadmapItemType.CAREER_PREPARATION, estimatedHours: 6 },
        { title: "Plan a next conversation", description: "Discuss options, constraints, and current requirements with a trusted counsellor or mentor.", itemType: RoadmapItemType.CAREER_PREPARATION, estimatedHours: 2 },
      ],
    },
  ];
}

async function seedReferenceData() {
  const categories = await Promise.all(
    CATEGORIES.map(([slug, name, description]) =>
      prisma.careerCategory.upsert({
        where: { slug },
        create: { slug, name, description },
        update: { name, description },
      }),
    ),
  );
  const categoriesBySlug = new Map(categories.map((category) => [category.slug, category]));

  const interestSlugs = new Set(CAREERS.flatMap((career) => Object.keys(career.fit.interestTargets)));
  const interests = await Promise.all(
    [...interestSlugs].map((slug) =>
      prisma.interest.upsert({
        where: { slug },
        create: { slug, name: labelFromSlug(slug) },
        update: { name: labelFromSlug(slug) },
      }),
    ),
  );
  const interestsBySlug = new Map(interests.map((interest) => [interest.slug, interest]));

  const uniqueSkills = new Map<string, SkillSeed>();
  for (const career of CAREERS) {
    for (const skill of career.skills) uniqueSkills.set(skill.slug, skill);
  }
  const skills = await Promise.all(
    [...uniqueSkills.values()].map((skill) =>
      prisma.skill.upsert({
        where: { slug: skill.slug },
        create: { slug: skill.slug, name: skill.name, category: skill.isTechnical ? "Technical" : "Professional" },
        update: { name: skill.name, category: skill.isTechnical ? "Technical" : "Professional" },
      }),
    ),
  );
  const skillsBySlug = new Map(skills.map((skill) => [skill.slug, skill]));

  return { categoriesBySlug, interestsBySlug, skillsBySlug };
}

async function seedCareers() {
  const { categoriesBySlug, interestsBySlug, skillsBySlug } = await seedReferenceData();

  for (const career of CAREERS) {
    const category = categoriesBySlug.get(career.category);
    if (!category) throw new Error(`Missing category '${career.category}' for ${career.slug}`);

    const record = await prisma.career.upsert({
      where: { slug: career.slug },
      create: {
        slug: career.slug,
        name: career.name,
        categoryId: category.id,
        overview: career.overview,
        whatProfessionalsDo: career.whatProfessionalsDo,
        whyChoose: career.whyChoose,
        educationSummary: career.educationSummary,
        salaryMinSample: career.salary[0],
        salaryMaxSample: career.salary[1],
        salaryDisclaimer: DEMO_SALARY_DISCLAIMER,
        demandLevel: career.demandLevel,
        demandDisclaimer: DEMO_DEMAND_DISCLAIMER,
        isDemoData: true,
        difficulty: career.difficulty,
        workLifeBalance: career.workLifeBalance,
        growthPotential: career.growthPotential,
        governmentOpportunity: career.governmentOpportunity,
        remoteWorkPotential: career.remoteWorkPotential,
        entranceExams: career.entranceExams,
        certifications: career.certifications,
        recommendedCourses: career.recommendedCourses,
        careerProgression: career.progression,
        relatedCareerSlugs: career.relatedCareers,
      },
      update: {
        name: career.name,
        categoryId: category.id,
        overview: career.overview,
        whatProfessionalsDo: career.whatProfessionalsDo,
        whyChoose: career.whyChoose,
        educationSummary: career.educationSummary,
        salaryMinSample: career.salary[0],
        salaryMaxSample: career.salary[1],
        salaryDisclaimer: DEMO_SALARY_DISCLAIMER,
        demandLevel: career.demandLevel,
        demandDisclaimer: DEMO_DEMAND_DISCLAIMER,
        isDemoData: true,
        difficulty: career.difficulty,
        workLifeBalance: career.workLifeBalance,
        growthPotential: career.growthPotential,
        governmentOpportunity: career.governmentOpportunity,
        remoteWorkPotential: career.remoteWorkPotential,
        entranceExams: career.entranceExams,
        certifications: career.certifications,
        recommendedCourses: career.recommendedCourses,
        careerProgression: career.progression,
        relatedCareerSlugs: career.relatedCareers,
      },
    });

    await prisma.careerFitProfile.upsert({
      where: { careerId: record.id },
      create: { careerId: record.id, ...career.fit },
      update: { ...career.fit },
    });

    await prisma.careerSkill.deleteMany({ where: { careerId: record.id } });
    await prisma.careerSkill.createMany({
      data: career.skills.map((skill) => {
        const skillRecord = skillsBySlug.get(skill.slug);
        if (!skillRecord) throw new Error(`Missing skill '${skill.slug}' for ${career.slug}`);
        return {
          careerId: record.id,
          skillId: skillRecord.id,
          targetLevel: skill.targetLevel,
          importance: skill.importance,
          isTechnical: skill.isTechnical ?? false,
        };
      }),
    });

    await prisma.careerInterest.deleteMany({ where: { careerId: record.id } });
    await prisma.careerInterest.createMany({
      data: Object.entries(career.fit.interestTargets).map(([slug, weight]) => {
        const interest = interestsBySlug.get(slug);
        if (!interest) throw new Error(`Missing interest '${slug}' for ${career.slug}`);
        return { careerId: record.id, interestId: interest.id, weight };
      }),
    });

    const roadmap = await prisma.careerRoadmap.upsert({
      where: { careerId: record.id },
      create: {
        careerId: record.id,
        title: `${career.name} roadmap`,
        description: "A flexible, sample learning plan. Confirm current requirements with relevant official sources.",
        estimatedWeeks: 24,
      },
      update: {
        title: `${career.name} roadmap`,
        description: "A flexible, sample learning plan. Confirm current requirements with relevant official sources.",
        estimatedWeeks: 24,
      },
    });

    await prisma.roadmapPhase.deleteMany({ where: { roadmapId: roadmap.id } });
    for (const [phaseIndex, phase] of createRoadmap(career).entries()) {
      await prisma.roadmapPhase.create({
        data: {
          roadmapId: roadmap.id,
          order: phaseIndex + 1,
          title: phase.title,
          description: phase.description,
          items: {
            create: phase.items.map((item, itemIndex) => ({
              order: itemIndex + 1,
              title: item.title,
              description: item.description,
              itemType: item.itemType,
              estimatedHours: item.estimatedHours,
            })),
          },
        },
      });
    }
  }
}

async function seedAssessmentQuestions() {
  for (const [index, question] of QUESTION_PROMPTS.entries()) {
    await prisma.assessmentQuestion.upsert({
      where: { slug: question.slug },
      create: {
        slug: question.slug,
        dimension: question.dimension,
        prompt: question.prompt,
        helperText: question.helperText,
        options: SCALE_OPTIONS,
        order: index + 1,
      },
      update: {
        dimension: question.dimension,
        prompt: question.prompt,
        helperText: question.helperText,
        options: SCALE_OPTIONS,
        order: index + 1,
        isActive: true,
      },
    });
  }
}

async function main() {
  await seedCareers();
  await seedAssessmentQuestions();
  console.info(`Seeded ${CAREERS.length} realistic demo careers and ${QUESTION_PROMPTS.length} assessment questions.`);
}

main()
  .catch((error: unknown) => {
    console.error("Failed to seed career data", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
